export const BACKEND_ERROR_CODES = {
    AUTH: {
        INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
        UNAUTHORIZED: 'UNAUTHORIZED',
        INVALID_TOKEN: 'INVALID_TOKEN',
        SESSION_EXPIRED: 'SESSION_EXPIRED',
        AUTH_REQUIRED: 'AUTH_REQUIRED',
        FORBIDDEN: 'FORBIDDEN',
        REG_INVALID_DATA: 'REG_INVALID_DATA',
        REGISTRATION_FAILED: 'REGISTRATION_FAILED',
        REG_USER_ALREADY_EXISTS: 'REG_USER_ALREADY_EXISTS',
        REG_CLAIM_FAILED: 'REG_CLAIM_FAILED',
        USER_ALREADY_EXISTS: 'UserAlreadyExistsCode',        
        DEFAULT_REGISTRATION_ERROR_CODE: 'DEFAULT_REGISTRATION_ERROR_CODE'
    },
    POST: {
        NOT_FOUND: 'POST_NOT_FOUND',
        SLUG_CATEGORY_REQUIRED: 'SLUG_AND_CATEGORY_REQUIRED',
        NOT_FOUND_MISMATCH: 'POST_NOT_FOUND_OR_CATEGORY_MISMATCH',
        ALREADY_EXISTS: 'POST_OR_SLUG_ALREADY_EXISTS',
        CONTENT_EMPTY: 'POST_CONTENT_IS_EMPTY',
    },
    CATEGORY: {
        NOT_FOUND: 'CATEGORY_NOT_FOUND',
        OR_SLUG_EXISTS: 'CATEGORY_OR_SLUG_EXISTS',        
        DELETE_BLOCKED: 'CATEGORY_DELETE_BLOCKED',
    },
    COMMENT: {
        NOT_FOUND: 'COMMENT_NOT_FOUND',
        ACCESS_DENIED: 'COMMENT_ACCESS_DENIED',
        EMPTY: 'COMMENT_IS_EMPTY',
    },
    INFRASTRUCTURE: {
        LIMIT_EXCEEDED: 'LIMIT_EXCEEDED'
    },
    SYSTEM: {
        VALIDATION_FAILED: 'VALIDATION_FAILED'
    }
} as const;

export const HTTP_STATUS = {
    NETWORK_ERROR: 0,
    OK: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    PAYLOAD_TOO_LARGE: 413,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504
} as const;

export const HTTP_HEADERS = {
    RETRY_AFTER: 'Retry-After',
    RATE_LIMIT: 'X-Rate-Limit-Limit'
} as const;